### PR TITLE
[WIP] Added QListControl::SelectAllItems()

### PR DESCRIPTION
**Pull request by lackovic10**
Related PR #639

tasks:
 - [x] add function `QListControl::SelectAllItems()`

### CODE REVIEW

**Comment by lackovic10** [comment]
@spekary do we have some tests for the QListControl class ?
i would like to write a test for `UnselectAllItems` and `SelectAllItems`, i haven't tested this code yet, that's why i marked the PR WIP.

**Comment by lackovic10** [comment]
what are the plans for the V3 release ? i would like to contribute a bit more if i find the time. There isn't any info on the [main page](https://github.com/qcubed/framework) about contributing. I think it would be very important to have contributing info on the main page to help grow the community

**Comment by spekary** [comment]
Tests are always welcome. See the framework/includes/tests folder. I would love to see some user interface testing using Codeception, but that would take some effort to pull together I think, and is currently slated for 3.1.

@vakopian and I are working through the last issues in the code generator, and then we should be at beta. There is still a lot to do after that:
* testing
* run through all the example pages and make sure they are working
* documentation
* there has been talk of a deployment helper that will separate put the assets under docroot, but all the included files would go outside of docroot, or at least the configuration directory.
* Redo the installation utility that would run immediately after a composer install.
* Moving old plugins to the new plugin system (though some structural changes might still be in order depending on the deployment system proposed)

**Comment by lackovic10** [comment]
ok so if i find time to work on some of these issues, on which branch should i work ?
i'll try to add unit tests here, so please don't merge before i do that.
do you have some central place of information where all this information is about releases, issues, etc ?
i've seen the facebook page, but there don't seem to be a lot of activity going on. i've seen the separate issues though, but i think it's hard to keep track like that ..

**Comment by lackovic10** [comment]
i have seen there are some tests. however i don't know how to run them. can you help out to speed me up ?
i'd just like to use `phpunit PATH_TO_FILE`

**Comment by lackovic10** [comment]
@spekary i don't know if you've seen my last comments, i forgot to tag you then, sorry.

**Pull request closed without merging**
