### PR TITLE
Bugfix small adjustments of style

### PR DESCRIPTION
**Pull request by kukrik**
1) Added and modified corepage.css.
2) One mistake removed at styles.css
3) Small tweaks at profile.php and error_dump.php

Reference: https://github.com/qcubed/framework/issues/1032

### CODE REVIEW

**Comment by kukrik** [comment]
This issue #1032 should not be overlooked. Profiling Information is not working as expected, if the encoding is inside. 

This issue needs to be resolved :(

**Comment by vaibhav-kaushal** [comment]
What changes are these?

**Comment by kukrik** [comment]
We agreed that a picture is better than a thousand words. I show before and after the changes.

**Before:**
before_1

**After:**
after_1

**Before:**
before_2

**After:**
after-2

**Before:**
before_3

**After:**
after_3

My mistake was that I put together two themes. My amendments relate only to the first topic.

Another topic that profiling Information is not working as expected, if the encoding is inside. 

Probably there will be a separate topic for this issue. But it is also an important issue!

Thoughts?

**Comment by kpirbhai** [comment]
@kukrik 
Are you referring to if the profiling output is within the main "Form" block that it doesn't work much of the time? If so, I've been having the problem as well. I've looked at it some but haven't had enough time to really dig in. I put RenderBegin and RenderEnd in the include header and footer respectively right after and before the body tags. I've gotten errors that $j and or jQuery aren't defined when clicking on the profiling output link.

**Comment by kukrik** [comment]
@kpirbhai, maybe I understand your question  correctly. This is another issue that I wanted to talk about. 

Database Profiling Tool does not work as expected when in configuration.inc.php is `'encoding' => 'utf8'` enabled.  It throws the error: MySqli Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET NAMES utf8' at line 1.

When `'encoding' => 'UTF-8'` is not active, it Database Profiling Tool works as expected.

I think the problem lies elsewhere, not what you thought?!

**Comment by kukrik** [comment]
I'll take back to patch bugfix-encoding ago.  I'm not sure whether this is a bug? My development server shows an error with app, but in production server not the problem.

Do we have to encoding and/or set_charset theme investigate?

The patch bugfix_small_adjustments_of_style can only merge

**Comment by olegabr** [comment]
This PR is pretty clear. Thank you, @kukrik!

**Pull request merged**
