### PR TITLE
QCheckBoxList - added CheckAll(), UncheckAll()

### PR DESCRIPTION
**Pull request by lackovic10**
Add functions `CheckAll()` and `UncheckAll()` to the `QCheckBoxList` class.

### CODE REVIEW

**Comment by lackovic10** [comment]
yes. do you want just one function and passing in the `$selected` parameter ?

**Comment by spekary** [comment]
There is already an UnselectAllItems, so leave that the same. Instead of passing in $selected, pass in blnMarkAsModified to mirror the UnselectAllItems call. In other words, have both functions.

**Comment by lackovic10** [comment]
sorry i don't find the function [UnselectAllItems](https://github.com/qcubed/framework/blob/master/includes/qcubed/_core/base_controls/QListControl.class.php) can you please point me to it ?

**Comment by spekary** [comment]
Its in the Alpha3 branch.

**Comment by spekary** [comment]
I see what happened. I will merge this to 2.2. We will need to do it a little differently for alpha3.

**Comment by lackovic10** [comment]
I will create a new PR for alpha3 like you asked

**Pull request merged**
