### PR TITLE
clean up file endings

### PR DESCRIPTION
**Pull request by kpirbhai**
Cleaned up the endings of all files to remove extraneous ?>
Also removed the ending ?> from the codegen templates

### CODE REVIEW

**Comment by olegabr** [comment]
@kpirbhai thank you for this work! How have you did it? With some script or command? Can you please share it? May be we can include it into our testing workflow in order to force this style for all new additions.

**Comment by vaibhav-kaushal** [comment]
@kpirbhai If you did it via script, we would love to see that one :) And this was pending since long!

**Comment by kpirbhai** [comment]
Lol. No script. I just literally went through every file. It was bugging me.  ;)

**Comment by vaibhav-kaushal** [comment]
@kpirbhai That must have taken some patience! Thanks :)

**Comment by nlomb** [comment]
@olegabr 
script to remove extraneous "?>"  or to refactor some other things ?
would bash/sed/awk be appropriate ?
can do if needed.

**Comment by olegabr** [comment]
@nlomb  script to remove extraneous "?>"  would be enough to start. then we can add one more check for travis: execute this script against the whole codebase and then call something like `diff -rq qcubed/ qcubed.processed/` and treat any difference as an error. It would prevent any regression in a sense of extraneous "?>"

**Pull request merged**
